<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="1" id="0" name="scripts" package="" skipped="0" tests="2" time="184.404">
    <testcase classname="scripts.k8s_scripts.test_ingress.TestIngressClusterIp" name="TestIngressClusterIp.test_ingress_ip_assignment[ci_k8s_sanity,k8s_sanity]" time="99.712" />

    <testcase classname="scripts.k8s_scripts.test_policy.TestNetworkPolicyServiceIngress" name="TestNetworkPolicyServiceIngress.test_ingress_rule_on_pod_with_service[ci_k8s_sanity,k8s_sanity]" time="159.051">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/tcutils/wrappers.py&quot;, line 179, in wrapper
    raise TestFailed(&quot;\n &quot;.join(errmsg))
tcutils.cores.TestFailed: Test failed: AssertionError
Python 3.6.8: /usr/bin/python3
Wed Feb 24 10:14:09 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=&lt;scripts.k8s_scripts.test_policy.TestNetworkPoli...vice[ci_k8s_sanity,k8s_sanity] id=0x7fbdc2698be0&gt;, *args=(), **kwargs={})
   80             log.info(&apos;Initial checks done. Running the testcase now&apos;)
   81             log.info(&apos;&apos;)
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = &lt;function TestNetworkPolicyServiceIngress.test_ingress_rule_on_pod_with_service&gt;
self = &lt;scripts.k8s_scripts.test_policy.TestNetworkPoli...vice[ci_k8s_sanity,k8s_sanity] id=0x7fbdc2698be0&gt;
args = ()
kwargs = {}

 /contrail-test/scripts/k8s_scripts/test_policy.py in test_ingress_rule_on_pod_with_service(self=&lt;scripts.k8s_scripts.test_policy.TestNetworkPoli...vice[ci_k8s_sanity,k8s_sanity] id=0x7fbdc2698be0&gt;)
 3179         assert self.validate_nginx_lb([self.web1_pod_ns1,self.web2_pod_ns1],
 3180                                       service_ns1.cluster_ip,
 3181                                       test_pod=self.client1_pod_ns2, expectation=False)
 3182         assert self.client2_pod_ns1.ping_with_certainty(self.client1_pod_ns1.pod_ip)
 3183         assert self.client1_pod_ns1.ping_with_certainty(self.client2_pod_ns1.pod_ip)
test_pod undefined
self = &lt;scripts.k8s_scripts.test_policy.TestNetworkPoli...vice[ci_k8s_sanity,k8s_sanity] id=0x7fbdc2698be0&gt;
self.client1_pod_ns2 = &lt;k8s.pod.PodFixture object&gt;
expectation undefined
AssertionError: 
    __cause__ = None
    __class__ = &lt;class &apos;AssertionError&apos;&gt;
    __context__ = None
    __delattr__ = &lt;method-wrapper &apos;__delattr__&apos; of AssertionError object&gt;
    __dict__ = {}
    __dir__ = &lt;built-in method __dir__ of AssertionError object&gt;
    __doc__ = &apos;Assertion failed.&apos;
    __eq__ = &lt;method-wrapper &apos;__eq__&apos; of AssertionError object&gt;
    __format__ = &lt;built-in method __format__ of AssertionError object&gt;
    __ge__ = &lt;method-wrapper &apos;__ge__&apos; of AssertionError object&gt;
    __getattribute__ = &lt;method-wrapper &apos;__getattribute__&apos; of AssertionError object&gt;
    __gt__ = &lt;method-wrapper &apos;__gt__&apos; of AssertionError object&gt;
    __hash__ = &lt;method-wrapper &apos;__hash__&apos; of AssertionError object&gt;
    __init__ = &lt;method-wrapper &apos;__init__&apos; of AssertionError object&gt;
    __init_subclass__ = &lt;built-in method __init_subclass__ of type object&gt;
    __le__ = &lt;method-wrapper &apos;__le__&apos; of AssertionError object&gt;
    __lt__ = &lt;method-wrapper &apos;__lt__&apos; of AssertionError object&gt;
    __ne__ = &lt;method-wrapper &apos;__ne__&apos; of AssertionError object&gt;
    __new__ = &lt;built-in method __new__ of type object&gt;
    __reduce__ = &lt;built-in method __reduce__ of AssertionError object&gt;
    __reduce_ex__ = &lt;built-in method __reduce_ex__ of AssertionError object&gt;
    __repr__ = &lt;method-wrapper &apos;__repr__&apos; of AssertionError object&gt;
    __setattr__ = &lt;method-wrapper &apos;__setattr__&apos; of AssertionError object&gt;
    __setstate__ = &lt;built-in method __setstate__ of AssertionError object&gt;
    __sizeof__ = &lt;built-in method __sizeof__ of AssertionError object&gt;
    __str__ = &lt;method-wrapper &apos;__str__&apos; of AssertionError object&gt;
    __subclasshook__ = &lt;built-in method __subclasshook__ of type object&gt;
    __suppress_context__ = False
    __traceback__ = &lt;traceback object&gt;
    args = ()
    with_traceback = &lt;built-in method with_traceback of AssertionError object&gt;

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File &quot;/contrail-test/tcutils/wrappers.py&quot;, line 82, in wrapper
    result = function(self, *args, **kwargs)
  File &quot;/contrail-test/scripts/k8s_scripts/test_policy.py&quot;, line 3181, in test_ingress_rule_on_pod_with_service
    test_pod=self.client1_pod_ns2, expectation=False)
AssertionError

</failure>

      <logfile>http://10.204.216.50/Docs/logs/2011-169_2021_02_24_10_10_28/logs//testnetworkpolicyserviceingress.html#test_ingress_rule_on_pod_with_service</logfile>
    </testcase>

    <properties>
      <property name="LogsLocation" value="http://10.204.216.50/Docs/logs/2011-169_2021_02_24_10_10_28/logs/" />
      <property name="Build" value="2011-169" />
      <property name="Report" value="http://10.204.216.50/Docs/logs/2011-169_2021_02_24_10_10_28/junit-noframes.html" />
      <property name="Topology" value="&lt;br/&gt;DISTRO : &quot;Ubuntu 18.04.5 LTS&quot; &lt;br/&gt;SKU :  &lt;br/&gt;Config Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Control Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Compute Nodes : [&apos;noden19&apos;, &apos;nodec9&apos;] &lt;br/&gt;Openstack Node : [&apos;noden20&apos;, &apos;nodei34&apos;] &lt;br/&gt;WebUI Node : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Analytics Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Database Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Physical Devices : [&apos;&apos;] &lt;br/&gt;" />
      <property name="cores" value="{&apos;192.168.7.20&apos;: [], &apos;192.168.7.29&apos;: [], &apos;192.168.7.34&apos;: [], &apos;192.168.7.19&apos;: [], &apos;192.168.7.9&apos;: [], &apos;192.168.7.18&apos;: []}" />
    </properties>
  </testsuite>
  <testsuite errors="0" failures="0" id="1" name="" package="" skipped="0" tests="0" time="3.522">
</testsuite>
</testsuites>
