<link href="txtsyle.css" rel="stylesheet" type="text/css" />2021-02-22 04:58:56,420 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 04:58:56,450 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 04:58:57,553 - INFO - Project ctest-SecurityGroupBasicRegressionTests1-30253305 not found, creating it
2021-02-22 04:58:58,163 - INFO - Created Project:ctest-SecurityGroupBasicRegressionTests1-30253305, ID : c91a91aa-01fd-4425-8a83-b7de098c4ed5 
2021-02-22 04:59:02,374 - INFO - ================================================================================
2021-02-22 04:59:02,375 - INFO - STARTING TEST    : test_sec_group_basic
2021-02-22 04:59:02,375 - INFO - TEST DESCRIPTION : 
        Description: Test basic SG features
            1. Security group create and delete
            2. Create security group with custom rules and then update it for tcp
            3. Launch VM with custom created security group and verify
            4. Remove secuity group association with VM
            5. Add back custom security group to VM and verify
            6. Try to delete security group with association to VM. It should fail.
            7. Test with ping, which should fail
            8. Test with TCP which should pass
            9. Update the rules to allow icmp, ping should pass now.
        
2021-02-22 04:59:03,723 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 04:59:03,723 - INFO - Initial checks done. Running the testcase now
2021-02-22 04:59:03,723 - INFO - 
2021-02-22 04:59:04,422 - INFO - Creating Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-30253305', 'ctest-test_sec_group-59057607']
2021-02-22 05:00:35,756 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:00:34 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function SecurityGroupBasicRegressionTests1.test_sec_group_basic>
self = <scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>
args = ()
kwargs = {}

 /contrail-test/scripts/securitygroup/test_regression_basic.py in test_sec_group_basic(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>)
   49                  }]
   50         #Create the SG
   51         sg_fixture = self.config_sec_group(name=secgrp_name, entries=rule)
   52         #Delete the SG
   53         self.delete_sec_group(sg_fixture)
sg_fixture undefined
self = <scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>
self.config_sec_group = <bound method BaseSGTest.config_sec_group of <sc...sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>>
name undefined
secgrp_name = 'ctest-test_sec_group-59057607'
entries undefined
rule = [{'direction': '>', 'dst_addresses': [{'subnet': {'ip_prefix': '77.202.155.128', 'ip_prefix_len': 26}}], 'dst_ports': [{'end_port': 8000, 'start_port': 8000}], 'protocol': 'udp', 'src_addresses': [{'security_group': 'local'}], 'src_ports': [{'end_port': 9000, 'start_port': 9000}]}]

 /contrail-test/common/securitygroup/base.py in config_sec_group(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>, name='ctest-test_sec_group-59057607', secgrpid=None, entries=[{'direction': '>', 'dst_addresses': [{'subnet': {'ip_prefix': '77.202.155.128', 'ip_prefix_len': 26}}], 'dst_ports': [{'end_port': 8000, 'start_port': 8000}], 'protocol': 'udp', 'src_addresses': [{'security_group': 'local'}], 'src_ports': [{'end_port': 9000, 'start_port': 9000}]}])
  193             self.connections, self.inputs.domain_name,
  194             self.inputs.project_name, secgrp_name=name,
  195             uuid=secgrpid, secgrp_entries=entries, option=option))
  196         result, msg = secgrp_fixture.verify_on_setup()
  197         assert result, msg
global uuid = <module 'uuid' from '/usr/lib64/python3.6/uuid.py'>
secgrpid = None
secgrp_entries undefined
entries = [{'direction': '>', 'dst_addresses': [{'subnet': {'ip_prefix': '77.202.155.128', 'ip_prefix_len': 26}}], 'dst_ports': [{'end_port': 8000, 'start_port': 8000}], 'protocol': 'udp', 'src_addresses': [{'security_group': 'local'}], 'src_ports': [{'end_port': 9000, 'start_port': 9000}]}]
option = 'neutron'

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>, fixture=<security_group.SecurityGroupFixture object>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f8fe9833668>, fixture=<security_group.SecurityGroupFixture object>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <security_group.SecurityGroupFixture object>
fixture.setUp = <bound method SecurityGroupFixture.setUp of <security_group.SecurityGroupFixture object>>

 /contrail-test/fixtures/security_group.py in setUp(self=<security_group.SecurityGroupFixture object>)
   52     def setUp(self):
   53         super(SecurityGroupFixture, self).setUp()
   54         self.create()
   55 
   56     def create(self):
self = <security_group.SecurityGroupFixture object>
self.create = <bound method SecurityGroupFixture.create of <security_group.SecurityGroupFixture object>>

 /contrail-test/fixtures/security_group.py in create(self=<security_group.SecurityGroupFixture object>)
   73                                                  parent_fqname=self.project_fq_name,
   74                                                  sg_entries=self.secgrp_entries,
   75                                                  option=self.option)
   76 
   77     @property
option undefined
self = <security_group.SecurityGroupFixture object>
self.option = 'neutron'

 /contrail-test/fixtures/openstack.py in create_security_group(self=<openstack.OpenstackOrchestrator object>, sg_name='ctest-test_sec_group-59057607', parent_fqname=['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-30253305'], sg_entries=[{'direction': '>', 'dst_addresses': [{'subnet': {'ip_prefix': '77.202.155.128', 'ip_prefix_len': 26}}], 'dst_ports': [{'end_port': 8000, 'start_port': 8000}], 'protocol': 'udp', 'src_addresses': [{'security_group': 'local'}], 'src_ports': [{'end_port': 9000, 'start_port': 9000}]}], option='neutron', **kwargs={})
  279            return super(OpenstackOrchestrator, self).create_security_group(sg_name=sg_name,
  280                                 parent_fqname=parent_fqname, sg_entries=sg_entries, **kwargs)
  281        sg = self.quantum_h.create_security_group(sg_name)
  282        if not sg:
  283            self.logger.error("security group creation failed through quantum")
sg undefined
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_security_group = <bound method QuantumHelper.create_security_group of <quantum_test.QuantumHelper object>>
sg_name = 'ctest-test_sec_group-59057607'

 /contrail-test/fixtures/quantum_test.py in create_security_group(self=<quantum_test.QuantumHelper object>, name='ctest-test_sec_group-59057607')
  197         try:
  198             sg_resp = self.obj.create_security_group(
  199                 {'security_group': sg_dict})
  200             return sg_resp['security_group']
  201         except CommonNetworkClientException as e:
sg_dict = {'description': 'SG-ctest-test_sec_group-59057607', 'name': 'ctest-test_sec_group-59057607'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_security_group(self=<neutronclient.v2_0.client.Client object>, body={'security_group': {'description': 'SG-ctest-test_sec_group-59057607', 'name': 'ctest-test_sec_group-59057607'}})
  981     def create_security_group(self, body=None):
  982         """Creates a new security group."""
  983         return self.post(self.security_groups_path, body=body)
  984 
  985     def update_security_group(self, security_group, body=None,
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.security_groups_path = '/security-groups'
body = {'security_group': {'description': 'SG-ctest-test_sec_group-59057607', 'name': 'ctest-test_sec_group-59057607'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/security-groups', body={'security_group': {'description': 'SG-ctest-test_sec_group-59057607', 'name': 'ctest-test_sec_group-59057607'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/security-groups', body='{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/security-groups', method='POST', **kwargs={'authenticated': True, 'body': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/security-groups'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/security-groups', 'POST'), **kwargs={'authenticated': True, 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/security-groups', 'POST')
kwargs = {'authenticated': True, 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/security-groups', method='POST', **kwargs={'authenticated': True, 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/security-groups'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/security-groups', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f8fe3fb3cf8>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/security-groups', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"security_group": {"name": "ctest-test_sec_grou...escription": "SG-ctest-test_sec_group-59057607"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'dd96d9650bff428abf40730fc009c71a'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/security-groups: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/securitygroup/test_regression_basic.py", line 51, in test_sec_group_basic
    sg_fixture = self.config_sec_group(name=secgrp_name, entries=rule)
  File "/contrail-test/common/securitygroup/base.py", line 195, in config_sec_group
    uuid=secgrpid, secgrp_entries=entries, option=option))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/security_group.py", line 54, in setUp
    self.create()
  File "/contrail-test/fixtures/security_group.py", line 75, in create
    option=self.option)
  File "/contrail-test/fixtures/openstack.py", line 281, in create_security_group
    sg = self.quantum_h.create_security_group(sg_name)
  File "/contrail-test/fixtures/quantum_test.py", line 199, in create_security_group
    {'security_group': sg_dict})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 983, in create_security_group
    return self.post(self.security_groups_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/security-groups: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:00:35,797 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:00:35,797 - INFO - 
<div id=test_sec_group_basic>2021-02-22 05:00:35,797 - INFO - END TEST : test_sec_group_basic : FAILED[0:01:33]
</div>2021-02-22 05:00:35,798 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:00:37,535 - INFO - Deleted project: ctest-SecurityGroupBasicRegressionTests1-30253305, ID : c91a91aa-01fd-4425-8a83-b7de098c4ed5 
2021-02-22 05:20:44,713 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:20:44,745 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:20:45,574 - INFO - Project ctest-SecurityGroupBasicRegressionTests1-50873328 not found, creating it
2021-02-22 05:20:46,413 - INFO - Created Project:ctest-SecurityGroupBasicRegressionTests1-50873328, ID : da4621fd-17df-46cd-9520-de8e4172d2e6 
2021-02-22 05:20:52,679 - INFO - ================================================================================
2021-02-22 05:20:52,679 - INFO - STARTING TEST    : test_sec_group_basic
2021-02-22 05:20:52,680 - INFO - TEST DESCRIPTION : 
        Description: Test basic SG features
            1. Security group create and delete
            2. Create security group with custom rules and then update it for tcp
            3. Launch VM with custom created security group and verify
            4. Remove secuity group association with VM
            5. Add back custom security group to VM and verify
            6. Try to delete security group with association to VM. It should fail.
            7. Test with ping, which should fail
            8. Test with TCP which should pass
            9. Update the rules to allow icmp, ping should pass now.
        
2021-02-22 05:20:54,038 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:20:54,038 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:20:54,038 - INFO - 
2021-02-22 05:20:54,631 - INFO - Creating Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255']
2021-02-22 05:20:56,417 - DEBUG - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255'] created succesfully
2021-02-22 05:20:56,417 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:20:57,276 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:20:57,345 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:20:57,389 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:20:57,454 - DEBUG - Requesting: https://192.168.7.20:8082/security-group/b5353ae9-1f13-4a43-adca-c77be1de7e15
2021-02-22 05:20:57,481 - INFO - Security group ctest-test_sec_group-82052255 found in the API Server
2021-02-22 05:20:57,481 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:20:57,501 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:20:57,540 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:20:57,608 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-22 05:20:57,647 - INFO - Validated that ACLs for Security group ctest-test_sec_group-82052255 are present in API Server
2021-02-22 05:20:57,648 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,663 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.20
2021-02-22 05:20:57,663 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,681 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.20
2021-02-22 05:20:57,681 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,778 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.29
2021-02-22 05:20:57,778 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,875 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.29
2021-02-22 05:20:57,876 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,892 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.34
2021-02-22 05:20:57,892 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:57,909 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.34
2021-02-22 05:20:57,909 - INFO - Validated SG ctest-test_sec_group-82052255 in Control nodes
2021-02-22 05:20:57,910 - INFO - Deleting Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255']
2021-02-22 05:20:58,108 - INFO - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255'] deleted successfully.
2021-02-22 05:20:58,109 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:20:58,131 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:20:58,170 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:20:58,228 - INFO - Security group ctest-test_sec_group-82052255 removed from the API Server
2021-02-22 05:20:58,229 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:20:58,247 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:20:58,283 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:20:58,343 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-22 05:20:58,383 - DEBUG - ACLs for Security group ctest-test_sec_group-82052255 removed from the API Server
2021-02-22 05:20:58,384 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,441 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.20
2021-02-22 05:20:58,441 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,501 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.20
2021-02-22 05:20:58,501 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,641 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.29
2021-02-22 05:20:58,641 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,781 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.29
2021-02-22 05:20:58,781 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,845 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.34
2021-02-22 05:20:58,845 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:20:58,909 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.34
2021-02-22 05:20:58,909 - INFO - Validated that SG ctest-test_sec_group-82052255 is not in control nodes
2021-02-22 05:20:58,930 - INFO - Creating Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255']
2021-02-22 05:21:00,526 - DEBUG - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255'] created succesfully
2021-02-22 05:21:00,526 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:21:00,549 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:21:00,588 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:21:00,647 - DEBUG - Requesting: https://192.168.7.20:8082/security-group/a0b681d7-bb2d-4146-aed9-29e3ead21060
2021-02-22 05:21:00,672 - INFO - Security group ctest-test_sec_group-82052255 found in the API Server
2021-02-22 05:21:00,672 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:21:00,694 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:21:00,732 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:21:00,792 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-22 05:21:00,834 - INFO - Validated that ACLs for Security group ctest-test_sec_group-82052255 are present in API Server
2021-02-22 05:21:00,835 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:00,852 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.20
2021-02-22 05:21:00,852 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:00,871 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.20
2021-02-22 05:21:00,872 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:00,972 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.29
2021-02-22 05:21:00,972 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:01,071 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.29
2021-02-22 05:21:01,072 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:01,089 - INFO - Validated that Security group ctest-test_sec_group-82052255 is found in control node 192.168.7.34
2021-02-22 05:21:01,089 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:21:01,106 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs found in the control node 192.168.7.34
2021-02-22 05:21:01,106 - INFO - Validated SG ctest-test_sec_group-82052255 in Control nodes
2021-02-22 05:21:01,107 - DEBUG - Replace all the rules of this security group ctest-test_sec_group-82052255 with the new rules
2021-02-22 05:21:01,107 - DEBUG - [{'protocol': 'tcp', 'dst_addresses': [{'subnet': {'ip_prefix': '123.246.51.128', 'ip_prefix_len': '26'}}], 'dst_ports': [{'start_port': 0, 'end_port': -1}], 'src_ports': [{'start_port': 0, 'end_port': -1}], 'src_addresses': [{'security_group': 'local'}]}, {'protocol': 'tcp', 'src_addresses': [{'subnet': {'ip_prefix': '123.246.51.128', 'ip_prefix_len': '26'}}], 'dst_ports': [{'start_port': 0, 'end_port': -1}], 'src_ports': [{'start_port': 0, 'end_port': -1}], 'dst_addresses': [{'security_group': 'local'}]}]
2021-02-22 05:22:31,910 - INFO - Deleting Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255']
2021-02-22 05:22:32,073 - INFO - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-50873328', 'ctest-test_sec_group-82052255'] deleted successfully.
2021-02-22 05:22:32,074 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:22:32,100 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:22:32,152 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:22:32,213 - INFO - Security group ctest-test_sec_group-82052255 removed from the API Server
2021-02-22 05:22:32,213 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:22:32,232 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:22:32,267 - DEBUG - Requesting: https://192.168.7.20:8082/project/da4621fd-17df-46cd-9520-de8e4172d2e6
2021-02-22 05:22:32,324 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-22 05:22:32,359 - DEBUG - ACLs for Security group ctest-test_sec_group-82052255 removed from the API Server
2021-02-22 05:22:32,360 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,417 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.20
2021-02-22 05:22:32,418 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,476 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.20
2021-02-22 05:22:32,476 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,541 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.29
2021-02-22 05:22:32,541 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,605 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.29
2021-02-22 05:22:32,605 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,665 - INFO - security group ctest-test_sec_group-82052255 removed from Control-node 192.168.7.34
2021-02-22 05:22:32,665 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-50873328:ctest-test_sec_group-82052255
2021-02-22 05:22:32,725 - DEBUG - Security group ctest-test_sec_group-82052255 ACLs removed from the control node 192.168.7.34
2021-02-22 05:22:32,725 - INFO - Validated that SG ctest-test_sec_group-82052255 is not in control nodes
2021-02-22 05:22:34,051 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:22:31 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function SecurityGroupBasicRegressionTests1.test_sec_group_basic>
self = <scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>
args = ()
kwargs = {}

 /contrail-test/scripts/securitygroup/test_regression_basic.py in test_sec_group_basic(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>)
   76         vn_fixture = self.useFixture(VNFixture(
   77             project_name=self.inputs.project_name, connections=self.connections,
   78             inputs=self.inputs, subnets=vn_net))
   79         assert vn_fixture.verify_on_setup()
   80         img_name = self.inputs.get_ci_image() or 'ubuntu-traffic'
inputs undefined
self = <scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
subnets undefined
vn_net = ['123.246.51.128/26']

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>, fixture=<vn_test.VNFixture object>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7f6ad6e3a6d8>, fixture=<vn_test.VNFixture object>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <vn_test.VNFixture object>
fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-SecurityGroupBasicRegressionTests1-50873328-77160809', subnets=[{'cidr': '123.246.51.128/26'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-SecurityGroupBasicRegressionTests1-50873328-77160809'
subnets = [{'cidr': '123.246.51.128/26'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-SecurityGroupBasicRegressionTests1-50873328-77160809', vn_subnets=[{'cidr': '123.246.51.128/26'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
   99                 net_req['provider:physical_network'] = sriov_provider_network
  100                 net_req['provider:segmentation_id'] = sriov_vlan
  101             net_rsp = self.obj.create_network({'network': net_req})
  102             self.logger.debug('Response for create_network : ' + repr(net_rsp))
  103 
net_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_network = <bound method Client.create_network of <neutronclient.v2_0.client.Client object>>
net_req = {'name': 'ctest-SecurityGroupBasicRegressionTests1-50873328-77160809'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_network(self=<neutronclient.v2_0.client.Client object>, body={'network': {'name': 'ctest-SecurityGroupBasicRegressionTests1-50873328-77160809'}})
  824     def create_network(self, body=None):
  825         """Creates a new network."""
  826         return self.post(self.networks_path, body=body)
  827 
  828     def update_network(self, network, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.networks_path = '/networks'
body = {'network': {'name': 'ctest-SecurityGroupBasicRegressionTests1-50873328-77160809'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/networks', body={'network': {'name': 'ctest-SecurityGroupBasicRegressionTests1-50873328-77160809'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/networks', body='{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/networks', method='POST', **kwargs={'authenticated': True, 'body': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/networks'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/networks', 'POST'), **kwargs={'authenticated': True, 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/networks', 'POST')
kwargs = {'authenticated': True, 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/networks', method='POST', **kwargs={'authenticated': True, 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/networks'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/networks', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f6ad55793c8>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/networks', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"network": {"name": "ctest-SecurityGroupBasicRegressionTests1-50873328-77160809"}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd97dca143ff4ca3ac28e2627e9f0e28'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/networks: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/securitygroup/test_regression_basic.py", line 78, in test_sec_group_basic
    inputs=self.inputs, subnets=vn_net))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 101, in create_network
    net_rsp = self.obj.create_network({'network': net_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 826, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/networks: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:22:34,090 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:22:34,090 - INFO - 
<div id=test_sec_group_basic>2021-02-22 05:22:34,091 - INFO - END TEST : test_sec_group_basic : FAILED[0:01:42]
</div>2021-02-22 05:22:34,091 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:22:36,409 - INFO - Deleted project: ctest-SecurityGroupBasicRegressionTests1-50873328, ID : da4621fd-17df-46cd-9520-de8e4172d2e6 
2021-02-24 06:21:50,073 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:21:50,111 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-24 06:21:52,573 - INFO - Project ctest-SecurityGroupBasicRegressionTests1-62790645 not found, creating it
2021-02-24 06:21:53,436 - INFO - Created Project:ctest-SecurityGroupBasicRegressionTests1-62790645, ID : 9b53e6fe-ca59-494d-9a63-48d1f770ab56 
2021-02-24 06:22:03,403 - INFO - ================================================================================
2021-02-24 06:22:03,404 - INFO - STARTING TEST    : test_sec_group_basic
2021-02-24 06:22:03,404 - INFO - TEST DESCRIPTION : 
        Description: Test basic SG features
            1. Security group create and delete
            2. Create security group with custom rules and then update it for tcp
            3. Launch VM with custom created security group and verify
            4. Remove secuity group association with VM
            5. Add back custom security group to VM and verify
            6. Try to delete security group with association to VM. It should fail.
            7. Test with ping, which should fail
            8. Test with TCP which should pass
            9. Update the rules to allow icmp, ping should pass now.
        
2021-02-24 06:22:04,751 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-24 06:22:04,752 - INFO - Initial checks done. Running the testcase now
2021-02-24 06:22:04,752 - INFO - 
2021-02-24 06:22:07,782 - INFO - Creating Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719']
2021-02-24 06:22:10,935 - DEBUG - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719'] created succesfully
2021-02-24 06:22:10,936 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:11,891 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:11,966 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:12,019 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:12,084 - DEBUG - Requesting: https://192.168.7.20:8082/security-group/a93a6a7d-82ae-4280-a105-b4baf6ca26a3
2021-02-24 06:22:12,117 - INFO - Security group ctest-test_sec_group-00234719 found in the API Server
2021-02-24 06:22:12,118 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:12,139 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:12,178 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:12,244 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-24 06:22:12,295 - INFO - Validated that ACLs for Security group ctest-test_sec_group-00234719 are present in API Server
2021-02-24 06:22:12,295 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,312 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.20
2021-02-24 06:22:12,313 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,332 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.20
2021-02-24 06:22:12,333 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,433 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.29
2021-02-24 06:22:12,433 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,532 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.29
2021-02-24 06:22:12,532 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,552 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.34
2021-02-24 06:22:12,553 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:12,571 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.34
2021-02-24 06:22:12,572 - INFO - Validated SG ctest-test_sec_group-00234719 in Control nodes
2021-02-24 06:22:12,572 - INFO - Deleting Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719']
2021-02-24 06:22:12,751 - INFO - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719'] deleted successfully.
2021-02-24 06:22:12,751 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:12,772 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:12,819 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:12,881 - INFO - Security group ctest-test_sec_group-00234719 removed from the API Server
2021-02-24 06:22:12,882 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:12,904 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:12,944 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:13,001 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-24 06:22:13,047 - DEBUG - ACLs for Security group ctest-test_sec_group-00234719 removed from the API Server
2021-02-24 06:22:13,047 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,105 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.20
2021-02-24 06:22:13,105 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,168 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.20
2021-02-24 06:22:13,169 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,308 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.29
2021-02-24 06:22:13,309 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,444 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.29
2021-02-24 06:22:13,445 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,505 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.34
2021-02-24 06:22:13,505 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:13,564 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.34
2021-02-24 06:22:13,565 - INFO - Validated that SG ctest-test_sec_group-00234719 is not in control nodes
2021-02-24 06:22:13,580 - INFO - Creating Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719']
2021-02-24 06:22:15,181 - DEBUG - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719'] created succesfully
2021-02-24 06:22:15,181 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:15,203 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:15,249 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:15,318 - DEBUG - Requesting: https://192.168.7.20:8082/security-group/c2f11031-40f1-40ca-82c5-0b54f03e2f8b
2021-02-24 06:22:15,345 - INFO - Security group ctest-test_sec_group-00234719 found in the API Server
2021-02-24 06:22:15,346 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:15,369 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:15,411 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:15,468 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-24 06:22:15,517 - INFO - Validated that ACLs for Security group ctest-test_sec_group-00234719 are present in API Server
2021-02-24 06:22:15,517 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,537 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.20
2021-02-24 06:22:15,537 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,556 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.20
2021-02-24 06:22:15,556 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,654 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.29
2021-02-24 06:22:15,655 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,751 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.29
2021-02-24 06:22:15,751 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,774 - INFO - Validated that Security group ctest-test_sec_group-00234719 is found in control node 192.168.7.34
2021-02-24 06:22:15,775 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:15,797 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs found in the control node 192.168.7.34
2021-02-24 06:22:15,797 - INFO - Validated SG ctest-test_sec_group-00234719 in Control nodes
2021-02-24 06:22:15,798 - DEBUG - Replace all the rules of this security group ctest-test_sec_group-00234719 with the new rules
2021-02-24 06:22:15,798 - DEBUG - [{'protocol': 'tcp', 'dst_addresses': [{'subnet': {'ip_prefix': '58.3.136.192', 'ip_prefix_len': '26'}}], 'dst_ports': [{'start_port': 0, 'end_port': -1}], 'src_ports': [{'start_port': 0, 'end_port': -1}], 'src_addresses': [{'security_group': 'local'}]}, {'protocol': 'tcp', 'src_addresses': [{'subnet': {'ip_prefix': '58.3.136.192', 'ip_prefix_len': '26'}}], 'dst_ports': [{'start_port': 0, 'end_port': -1}], 'src_ports': [{'start_port': 0, 'end_port': -1}], 'dst_addresses': [{'security_group': 'local'}]}]
2021-02-24 06:22:17,461 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-SecurityGroupBasicRegressionTests1-62790645-04258639'], 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-04258639', 'admin_state_up': True, 'tenant_id': '9b53e6feca59494d9a6348d1f770ab56', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '9b53e6feca59494d9a6348d1f770ab56', 'id': 'b578f995-9958-4f78-9721-117fd9c24e70', 'description': ''}}
2021-02-24 06:22:17,766 - ERROR - Neutron Exception while creating subnet for vn with id b578f995-9958-4f78-9721-117fd9c24e70
Traceback (most recent call last):
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
neutronclient.common.exceptions.InternalServerError: The server has either erred or is incapable of performing the requested operation.<br /><br />



Neutron server returns request_ids: ['req-6d9816d3-5d81-4642-b773-d0722cb857d3']
2021-02-24 06:22:17,821 - INFO - Created VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:17,854 - DEBUG - VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 UUID is b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:17,965 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:17,990 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:18,031 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:18,094 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,125 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,153 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:18,183 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:18,203 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/03c19be5-e355-4001-a822-b1252c6def74
2021-02-24 06:22:18,224 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:18,225 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,250 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:18,296 - INFO - Verified VN network id 13 for VN b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,296 - INFO - Verifications in API Server for VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 passed
2021-02-24 06:22:18,296 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,326 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:18,345 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:18,375 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/03c19be5-e355-4001-a822-b1252c6def74
2021-02-24 06:22:18,404 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,421 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '13076475938988380024', 'uuid-lslong': '10890004614770478704'}, 'enable': 'true', 'created': '2021-02-24T06:22:18', 'last-modified': '2021-02-24T06:22:18', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.009594'}
2021-02-24 06:22:18,421 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,440 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:18,440 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,537 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '13076475938988380024', 'uuid-lslong': '10890004614770478704'}, 'enable': 'true', 'created': '2021-02-24T06:22:18', 'last-modified': '2021-02-24T06:22:18', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.125483'}
2021-02-24 06:22:18,537 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,657 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:18,658 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,677 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '13076475938988380024', 'uuid-lslong': '10890004614770478704'}, 'enable': 'true', 'created': '2021-02-24T06:22:18', 'last-modified': '2021-02-24T06:22:18', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.267187'}
2021-02-24 06:22:18,677 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:18,696 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:18,696 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 passed
2021-02-24 06:22:18,697 - DEBUG - ====Verifying policy data for ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 in API_Server ======
2021-02-24 06:22:18,697 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:18,722 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:18,767 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:18,825 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/b578f995-9958-4f78-9721-117fd9c24e70
2021-02-24 06:22:18,855 - DEBUG - =>VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 has no policy to be verified
2021-02-24 06:22:18,855 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:18,855 - DEBUG - Verifying the admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:18,855 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:20,985 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:21,375 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639?flat', 'name': 'admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639'}
2021-02-24 06:22:21,375 - DEBUG - Verifying the admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:21,376 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:21,963 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:22,191 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639?flat', 'name': 'admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639'}
2021-02-24 06:22:22,191 - DEBUG - Verifying the admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:22,192 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:22,776 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:23,028 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639?flat', 'name': 'admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639'}
2021-02-24 06:22:23,028 - INFO - Validated that VN admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 is found in opserver
2021-02-24 06:22:23,085 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:23,110 - DEBUG - VRF ids for VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639: {}
2021-02-24 06:22:23,627 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-24 06:22:24,928 - INFO - Deleting VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 
2021-02-24 06:22:25,168 - DEBUG - Response for deleting network ()
2021-02-24 06:22:25,168 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e7f6dd28-f76d-450a-868d-ae7cf18b1da5
2021-02-24 06:22:25,196 - DEBUG - Response Code: 404
2021-02-24 06:22:25,197 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:25,219 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:25,263 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:25,324 - INFO - Validated that VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 is not found in API Server
2021-02-24 06:22:25,361 - DEBUG - VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 is not present in Agent 192.168.7.19 
2021-02-24 06:22:25,388 - DEBUG - VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 is not present in Agent 192.168.7.9 
2021-02-24 06:22:25,388 - INFO - Validated that VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 is not in any agent
2021-02-24 06:22:25,420 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:25,480 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:25,545 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:25,601 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-SecurityGroupBasicRegressionTests1-62790645-04258639
2021-02-24 06:22:25,671 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-SecurityGroupBasicRegressionTests1-62790645-04258639 info
2021-02-24 06:22:25,671 - INFO - Deleting Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719']
2021-02-24 06:22:25,841 - INFO - Security group: ['admin_domain', 'ctest-SecurityGroupBasicRegressionTests1-62790645', 'ctest-test_sec_group-00234719'] deleted successfully.
2021-02-24 06:22:25,841 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:25,873 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:25,916 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:25,968 - DEBUG - Requesting: https://192.168.7.20:8082/security-group/c2f11031-40f1-40ca-82c5-0b54f03e2f8b
2021-02-24 06:22:25,985 - DEBUG - Response Code: 404
2021-02-24 06:22:25,985 - INFO - Security group ctest-test_sec_group-00234719 removed from the API Server
2021-02-24 06:22:25,985 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:26,006 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:26,052 - DEBUG - Requesting: https://192.168.7.20:8082/project/9b53e6fe-ca59-494d-9a63-48d1f770ab56
2021-02-24 06:22:26,107 - DEBUG - Requesting: https://192.168.7.20:8082/access-control-lists
2021-02-24 06:22:26,153 - DEBUG - ACLs for Security group ctest-test_sec_group-00234719 removed from the API Server
2021-02-24 06:22:26,153 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,209 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.20
2021-02-24 06:22:26,209 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,269 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.20
2021-02-24 06:22:26,269 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,409 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.29
2021-02-24 06:22:26,409 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,549 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.29
2021-02-24 06:22:26,549 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=security_group&search_string=security-group:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,613 - INFO - security group ctest-test_sec_group-00234719 removed from Control-node 192.168.7.34
2021-02-24 06:22:26,613 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=access-control-list&search_string=access-control-list:admin_domain:ctest-SecurityGroupBasicRegressionTests1-62790645:ctest-test_sec_group-00234719
2021-02-24 06:22:26,673 - DEBUG - Security group ctest-test_sec_group-00234719 ACLs removed from the control node 192.168.7.34
2021-02-24 06:22:26,673 - INFO - Validated that SG ctest-test_sec_group-00234719 is not in control nodes
2021-02-24 06:22:27,963 - ERROR - BadRequest
Python 3.6.8: /usr/bin/python3
Wed Feb 24 06:22:24 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7fdd33dac7b8>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function SecurityGroupBasicRegressionTests1.test_sec_group_basic>
self = <scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7fdd33dac7b8>
args = ()
kwargs = {}

 /contrail-test/scripts/securitygroup/test_regression_basic.py in test_sec_group_basic(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7fdd33dac7b8>)
   99             vm1_fixture = self.useFixture(VMFixture(
  100                 project_name=self.inputs.project_name, connections=self.connections,
  101                 vn_obj=vn_fixture.obj, image_name=img_name, flavor='contrail_flavor_small',sg_ids=[secgrp_id]))
  102             vm2_fixture = self.useFixture(VMFixture(
  103                 project_name=self.inputs.project_name, connections=self.connections,
vn_obj undefined
vn_fixture = <vn_test.VNFixture object>
vn_fixture.obj = {'network': {'status': 'ACTIVE', 'router:externa...9958-4f78-9721-117fd9c24e70', 'description': ''}}
image_name undefined
img_name = 'ubuntu-traffic'
flavor undefined
sg_ids undefined
secgrp_id = 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7fdd33dac7b8>, fixture=<VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'novaclient.exceptions.BadRequest'>, BadRequest(), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'novaclient.exceptions.BadRequest'>, exc_obj=BadRequest(), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = BadRequest()
exc_obj.with_traceback = <built-in method with_traceback of BadRequest object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.securitygroup.test_regression_basic.Sec..._sanity,sanity,suite1,vcenter] id=0x7fdd33dac7b8>, fixture=<VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>
fixture.setUp = <bound method VMFixture.setUp of <VMFixture: cte...ityGroupBasicRegressionTests1-62790645-82874975>>

 /contrail-test/fixtures/vm_test.py in setUp(self=<VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>)
  207     def setUp(self):
  208         super(VMFixture, self).setUp()
  209         self.create()
  210 
  211     def create(self):
self = <VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>
self.create = <bound method VMFixture.create of <VMFixture: ct...ityGroupBasicRegressionTests1-62790645-82874975>>

 /contrail-test/fixtures/vm_test.py in create(self=<VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>)
  260                     userdata=self.userdata,
  261                     port_ids=self.port_ids,
  262                     fixed_ips=self.fixed_ips)
  263                 self.created = True
  264                 self.vm_obj = objs[0]
fixed_ips undefined
self = <VMFixture: ctest-SecurityGroupBasicRegressionTests1-62790645-82874975>
self.fixed_ips = []

 /contrail-test/fixtures/openstack.py in create_vm(self=<openstack.OpenstackOrchestrator object>, vm_name='ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', image_name='ubuntu-traffic', vn_objs=[{'network': {'status': 'ACTIVE', 'router:externa...9958-4f78-9721-117fd9c24e70', 'description': ''}}], **kwargs={'count': 1, 'fixed_ips': [], 'flavor': 'contrail_flavor_small', 'node_name': None, 'port_ids': [], 'project_uuid': '9b53e6fe-ca59-494d-9a63-48d1f770ab56', 'sg_ids': ['c2f11031-40f1-40ca-82c5-0b54f03e2f8b'], 'userdata': None, 'zone': None})
  138            except Exception as e:
  139                vn_ids.append(vn.uuid) #For the case of VcenterVN obnect in vrouter gw case
  140        return self.nova_h.create_vm(vm_name=vm_name, image_name=image_name, vn_ids=vn_ids, **kwargs)
  141 
  142    def delete_vm(self, vm_obj, **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.nova_h = <nova_test.NovaHelper object>
self.nova_h.create_vm = <bound method NovaHelper.create_vm of <nova_test.NovaHelper object>>
vm_name = 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975'
image_name = 'ubuntu-traffic'
vn_ids = ['b578f995-9958-4f78-9721-117fd9c24e70']
kwargs = {'count': 1, 'fixed_ips': [], 'flavor': 'contrail_flavor_small', 'node_name': None, 'port_ids': [], 'project_uuid': '9b53e6fe-ca59-494d-9a63-48d1f770ab56', 'sg_ids': ['c2f11031-40f1-40ca-82c5-0b54f03e2f8b'], 'userdata': None, 'zone': None}

 /contrail-test/fixtures/nova_test.py in create_vm(self=<nova_test.NovaHelper object>, project_uuid='9b53e6fe-ca59-494d-9a63-48d1f770ab56', image_name='ubuntu-traffic', vm_name='ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', vn_ids=['b578f995-9958-4f78-9721-117fd9c24e70'], node_name='nodec9', sg_ids=['c2f11031-40f1-40ca-82c5-0b54f03e2f8b'], count=1, userdata=None, flavor=<Flavor: contrail_flavor_small>, port_ids=[], fixed_ips=[], zone='nova:nodec9')
  615                                 config_drive=config_drive,
  616                                 key_name=self.key, availability_zone=zone,
  617                                 min_count=count, max_count=count, userdata=userdata)
  618         vm_objs = self.get_vm_list(name_pattern=vm_name,
  619                                    project_id=project_uuid)
min_count undefined
count = 1
max_count undefined
userdata = None

 /usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py in create(self=<novaclient.v2.servers.ServerManager object>, name='ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', image=<RequestIdProxy at 0x7fdd324d2e88 for image>, flavor=<Flavor: contrail_flavor_small>, meta=None, files=None, reservation_id=False, min_count=1, max_count=1, security_groups=['c2f11031-40f1-40ca-82c5-0b54f03e2f8b'], userdata=None, key_name='ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', availability_zone='nova:nodec9', block_device_mapping=None, block_device_mapping_v2=None, nics=[{'net-id': 'b578f995-9958-4f78-9721-117fd9c24e70'}], scheduler_hints=None, config_drive=False, disk_config=None, admin_pass=None, access_ip_v4=None, access_ip_v6=None, trusted_image_certificates=None, host=None, hypervisor_hostname=None, **kwargs={})
 1479 
 1480         response_key = "server" if not reservation_id else "reservation_id"
 1481         return self._boot(response_key, *boot_args, **boot_kwargs)
 1482 
 1483     @api_versions.wraps("2.0", "2.18")
self = <novaclient.v2.servers.ServerManager object>
self._boot = <bound method ServerManager._boot of <novaclient.v2.servers.ServerManager object>>
response_key = 'server'
boot_args = ['ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', <RequestIdProxy at 0x7fdd324d2e88 for image>, <Flavor: contrail_flavor_small>]
boot_kwargs = {'access_ip_v4': None, 'access_ip_v6': None, 'admin_pass': None, 'availability_zone': 'nova:nodec9', 'config_drive': False, 'disk_config': None, 'files': None, 'host': None, 'hypervisor_hostname': None, 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', ...}

 /usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py in _boot(self=<novaclient.v2.servers.ServerManager object>, response_key='server', name='ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', image=<RequestIdProxy at 0x7fdd324d2e88 for image>, flavor=<Flavor: contrail_flavor_small>, meta=None, files=None, userdata=None, reservation_id=False, return_raw=False, min_count=1, max_count=1, security_groups=['c2f11031-40f1-40ca-82c5-0b54f03e2f8b'], key_name='ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', availability_zone='nova:nodec9', block_device_mapping=None, block_device_mapping_v2=None, nics=[{'net-id': 'b578f995-9958-4f78-9721-117fd9c24e70'}], scheduler_hints=None, config_drive=False, admin_pass=None, disk_config=None, access_ip_v4=None, access_ip_v6=None, description=None, tags=None, trusted_image_certificates=None, host=None, hypervisor_hostname=None, **kwargs={})
  844 
  845         return self._create('/servers', body, response_key,
  846                             return_raw=return_raw, **kwargs)
  847 
  848     def get(self, server):
return_raw = False
kwargs = {}

 /usr/local/lib/python3.6/site-packages/novaclient/base.py in _create(self=<novaclient.v2.servers.ServerManager object>, url='/servers', body={'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', 'networks': [{'uuid': 'b578f995-9958-4f78-9721-117fd9c24e70'}], 'security_groups': [{'name': 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'}]}}, response_key='server', return_raw=False, obj_class=None, **kwargs={})
  362                 obj_class=None, **kwargs):
  363         self.run_hooks('modify_body_for_create', body, **kwargs)
  364         resp, body = self.api.client.post(url, body=body)
  365         if return_raw:
  366             return self.convert_into_with_meta(body[response_key], resp)
resp undefined
body = {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', 'networks': [{'uuid': 'b578f995-9958-4f78-9721-117fd9c24e70'}], 'security_groups': [{'name': 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'}]}}
self = <novaclient.v2.servers.ServerManager object>
self.api = <novaclient.v2.client.Client object>
self.api.client = <novaclient.client.SessionClient object>
self.api.client.post = <bound method Adapter.post of <novaclient.client.SessionClient object>>
url = '/servers'

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in post(self=<novaclient.client.SessionClient object>, url='/servers', **kwargs={'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', 'networks': [{'uuid': 'b578f995-9958-4f78-9721-117fd9c24e70'}], 'security_groups': [{'name': 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'}]}}})
  390 
  391     def post(self, url, **kwargs):
  392         return self.request(url, 'POST', **kwargs)
  393 
  394     def put(self, url, **kwargs):
self = <novaclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <novaclient.client.SessionClient object>>
url = '/servers'
kwargs = {'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', 'networks': [{'uuid': 'b578f995-9958-4f78-9721-117fd9c24e70'}], 'security_groups': [{'name': 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'}]}}}

 /usr/local/lib/python3.6/site-packages/novaclient/client.py in request(self=<novaclient.client.SessionClient object>, url='/servers', method='POST', **kwargs={'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-SecurityGroupBasicRegressionTests1-6...t-SecurityGroupBasicRegressionTests1-62790645key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-SecurityGroupBasicRegressionTests1-62790645-82874975', 'networks': [{'uuid': 'b578f995-9958-4f78-9721-117fd9c24e70'}], 'security_groups': [{'name': 'c2f11031-40f1-40ca-82c5-0b54f03e2f8b'}]}}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': '8db414407ae04cb49eeffc0b13763c88'}})
   76         # api_versions.check_headers(resp, self.api_version)
   77         if raise_exc and resp.status_code >= 400:
   78             raise exceptions.from_response(resp, body, url, method)
   79 
   80         return resp, body
global exceptions = <module 'novaclient.exceptions' from '/usr/local...ython3.6/site-packages/novaclient/exceptions.py'>
exceptions.from_response = <function from_response>
resp = <Response [400]>
body = {'badRequest': {'code': 400, 'message': 'Network b578f995-9958-4f78-9721-117fd9c24e70 requires a subnet in order to boot instances on.'}}
url = '/servers'
method = 'POST'
BadRequest: Network b578f995-9958-4f78-9721-117fd9c24e70 requires a subnet in order to boot instances on. (HTTP 400) (Request-ID: req-b05067f7-d5c4-4b69-8bae-f448c4fe9065)
    __cause__ = None
    __class__ = <class 'novaclient.exceptions.BadRequest'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of BadRequest object>
    __dict__ = {'code': 400, 'details': None, 'message': 'Network b578f995-9958-4f78-9721-117fd9c24e70 requires a subnet in order to boot instances on.', 'method': 'POST', 'request_id': 'req-b05067f7-d5c4-4b69-8bae-f448c4fe9065', 'url': '/servers'}
    __dir__ = <built-in method __dir__ of BadRequest object>
    __doc__ = '\n    HTTP 400 - Bad request: you sent some malformed data.\n    '
    __eq__ = <method-wrapper '__eq__' of BadRequest object>
    __format__ = <built-in method __format__ of BadRequest object>
    __ge__ = <method-wrapper '__ge__' of BadRequest object>
    __getattribute__ = <method-wrapper '__getattribute__' of BadRequest object>
    __gt__ = <method-wrapper '__gt__' of BadRequest object>
    __hash__ = <method-wrapper '__hash__' of BadRequest object>
    __init__ = <bound method ClientException.__init__ of BadRequest()>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of BadRequest object>
    __lt__ = <method-wrapper '__lt__' of BadRequest object>
    __module__ = 'novaclient.exceptions'
    __ne__ = <method-wrapper '__ne__' of BadRequest object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of BadRequest object>
    __reduce_ex__ = <built-in method __reduce_ex__ of BadRequest object>
    __repr__ = <method-wrapper '__repr__' of BadRequest object>
    __setattr__ = <method-wrapper '__setattr__' of BadRequest object>
    __setstate__ = <built-in method __setstate__ of BadRequest object>
    __sizeof__ = <built-in method __sizeof__ of BadRequest object>
    __str__ = <bound method ClientException.__str__ of BadRequest()>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ()
    code = 400
    details = None
    http_status = 400
    message = 'Network b578f995-9958-4f78-9721-117fd9c24e70 requires a subnet in order to boot instances on.'
    method = 'POST'
    request_id = 'req-b05067f7-d5c4-4b69-8bae-f448c4fe9065'
    url = '/servers'
    with_traceback = <built-in method with_traceback of BadRequest object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/securitygroup/test_regression_basic.py", line 101, in test_sec_group_basic
    vn_obj=vn_fixture.obj, image_name=img_name, flavor='contrail_flavor_small',sg_ids=[secgrp_id]))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vm_test.py", line 209, in setUp
    self.create()
  File "/contrail-test/fixtures/vm_test.py", line 262, in create
    fixed_ips=self.fixed_ips)
  File "/contrail-test/fixtures/openstack.py", line 140, in create_vm
    return self.nova_h.create_vm(vm_name=vm_name, image_name=image_name, vn_ids=vn_ids, **kwargs)
  File "/contrail-test/fixtures/nova_test.py", line 617, in create_vm
    min_count=count, max_count=count, userdata=userdata)
  File "/usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1481, in create
    return self._boot(response_key, *boot_args, **boot_kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py", line 846, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/base.py", line 364, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/client.py", line 78, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.BadRequest: Network b578f995-9958-4f78-9721-117fd9c24e70 requires a subnet in order to boot instances on. (HTTP 400) (Request-ID: req-b05067f7-d5c4-4b69-8bae-f448c4fe9065)



2021-02-24 06:22:27,993 - DEBUG - No XMPP flaps were noticed during the test
2021-02-24 06:22:27,994 - INFO - 
<div id=test_sec_group_basic>2021-02-24 06:22:27,994 - INFO - END TEST : test_sec_group_basic : FAILED[0:00:24]
</div>2021-02-24 06:22:27,994 - INFO - --------------------------------------------------------------------------------
2021-02-24 06:22:32,715 - INFO - Deleted project: ctest-SecurityGroupBasicRegressionTests1-62790645, ID : 9b53e6fe-ca59-494d-9a63-48d1f770ab56 
