2021-02-18 11:35:41,356 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-18 11:35:41,387 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-18 11:35:42,237 - INFO - Project ctest-TestvDNSBasic0-74672136 not found, creating it
2021-02-18 11:35:42,873 - INFO - Created Project:ctest-TestvDNSBasic0-74672136, ID : e7a1dac9-dcf1-4e37-bfe2-7a87008dcebd 
2021-02-18 11:35:46,708 - INFO - ================================================================================
2021-02-18 11:35:46,708 - INFO - STARTING TEST    : test_vdns_ping_same_vn
2021-02-18 11:35:46,709 - INFO - TEST DESCRIPTION : 
        Test:- Test vdns functionality. On VM launch agent should dynamically update dns records to dns agent
            1.  Create vDNS server
            2.  Create IPAM using above vDNS data
            3.  Create VN using above IPAM and launch 2 VM's within it
            4.  Ping between these 2 VM's using dns name
            5.  Try to delete vDNS server which has IPAM back-reference[Negative case]
            6.  Add CNAME VDNS record for vm1-test and verify we able to ping by alias name
        Pass criteria: Step 4,5 and 6 should pass

        Maintainer: cf-test@juniper.net
        
2021-02-18 11:35:48,063 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.34': '0', '192.168.27.20': '0'}, '192.168.7.9': {'192.168.27.20': '2', '192.168.27.34': '3'}} with
2021-02-18 11:35:48,063 - INFO - Initial checks done. Running the testcase now
2021-02-18 11:35:48,063 - INFO - 
2021-02-18 11:35:49,701 - INFO - Using existing project ['admin_domain', 'ctest-TestvDNSBasic0-74672136'](e7a1dac9-dcf1-4e37-bfe2-7a87008dcebd)
2021-02-18 11:35:49,820 - DEBUG - Creating VDNS : ctest-vdns1-34558867
2021-02-18 11:35:49,919 - DEBUG - VDNS: ['admin_domain', 'ctest-vdns1-34558867'] created succesfully
2021-02-18 11:35:49,920 - DEBUG - Verify VDNS entry is shown in control node
2021-02-18 11:35:49,974 - DEBUG - Verify VDNS entry is shown in the API server
2021-02-18 11:35:49,975 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-18 11:35:51,213 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-18 11:35:51,292 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-18 11:35:51,334 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-DNS/e4fbbbd0-9059-48d0-aff4-5e0506b9ebef
2021-02-18 11:35:52,797 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestvDNSBasic0-74672136', 'ctest-vn1-vdns-92227502'], 'name': 'ctest-vn1-vdns-92227502', 'admin_state_up': True, 'tenant_id': 'e7a1dac9dcf14e37bfe27a87008dcebd', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'e7a1dac9dcf14e37bfe27a87008dcebd', 'id': 'f14dd890-11a2-49fb-9add-31831038a179', 'description': ''}}
2021-02-18 11:35:53,358 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'f14dd890-11a2-49fb-9add-31831038a179', 'tenant_id': 'e7a1dac9dcf14e37bfe27a87008dcebd', 'created_at': '2021-02-18T11:35:53.390429', 'dns_nameservers': [], 'updated_at': '2021-02-18T11:35:53.390429', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '10.10.10.2', 'end': '10.10.10.254'}], 'gateway_ip': '10.10.10.1', 'dns_server_address': '10.10.10.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '10.10.10.0/24', 'id': '00ea7cc7-fac0-474e-ba7d-a5fae76c0196'}}
2021-02-18 11:35:53,417 - INFO - Created VN ctest-vn1-vdns-92227502
2021-02-18 11:35:53,445 - DEBUG - VN ctest-vn1-vdns-92227502 UUID is f14dd890-11a2-49fb-9add-31831038a179
2021-02-18 11:35:54,224 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-18 11:35:57,197 - INFO - VM ([<Server: ctest-vm1-test-05206063>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-18 11:35:57,197 - INFO - Waiting for VM ctest-vm1-test-05206063 to be up..
2021-02-18 11:35:57,284 - DEBUG - VM <Server: ctest-vm1-test-05206063> is still in BUILD state, Expected: ACTIVE
2021-02-18 11:36:02,415 - DEBUG - VM <Server: ctest-vm1-test-05206063> is still in BUILD state, Expected: ACTIVE
2021-02-18 11:36:07,544 - DEBUG - VM <Server: ctest-vm1-test-05206063> is still in BUILD state, Expected: ACTIVE
2021-02-18 11:36:12,756 - DEBUG - VM <Server: ctest-vm1-test-05206063> is still in BUILD state, Expected: ACTIVE
2021-02-18 11:36:17,960 - DEBUG - VM <Server: ctest-vm1-test-05206063> is in ACTIVE state now
2021-02-18 11:36:17,961 - INFO - VM name : ctest-vm1-test-05206063
2021-02-18 11:36:18,173 - DEBUG - VM ctest-vm1-test-05206063 ID is a015aa9e-717b-4dd6-a66b-544b06b64a71
2021-02-18 11:36:18,174 - DEBUG - VM ctest-vm1-test-05206063 launched on Node nodec9.maas
2021-02-18 11:36:18,368 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/a015aa9e-717b-4dd6-a66b-544b06b64a71
2021-02-18 11:36:18,958 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/a015aa9e-717b-4dd6-a66b-544b06b64a71
2021-02-18 11:36:19,047 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine-interface/b1f3f0c8-1eb7-4989-a804-6a21d781f9c4
2021-02-18 11:36:22,291 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1017ms')
2021-02-18 11:36:22,292 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:22,331 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:26,385 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1026ms')
2021-02-18 11:36:26,386 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:26,427 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:30,487 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1019ms')
2021-02-18 11:36:30,487 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:30,522 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:34,578 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1027ms')
2021-02-18 11:36:34,579 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:34,619 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:38,670 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1024ms')
2021-02-18 11:36:38,670 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:38,704 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:42,771 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1030ms')
2021-02-18 11:36:42,771 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:42,802 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:46,869 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1030ms')
2021-02-18 11:36:46,869 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:46,896 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:50,962 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1026ms')
2021-02-18 11:36:50,962 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:51,002 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:55,062 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1021ms')
2021-02-18 11:36:55,063 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:55,099 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:36:59,156 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1024ms')
2021-02-18 11:36:59,156 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:36:59,188 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:03,254 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1026ms')
2021-02-18 11:37:03,254 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:37:03,285 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:07,312 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 999ms')
2021-02-18 11:37:07,312 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:37:07,356 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:11,447 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1023ms')
2021-02-18 11:37:11,447 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:37:11,481 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:15,544 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1022ms')
2021-02-18 11:37:15,545 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:37:15,582 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:19,632 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1014ms')
2021-02-18 11:37:19,633 - DEBUG - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 failed!
2021-02-18 11:37:19,674 - DEBUG - Gateway for vn admin_domain:ctest-TestvDNSBasic0-74672136:ctest-vn1-vdns-92227502 is 10.10.10.1 and allocation pool is NOT set
2021-02-18 11:37:21,728 - DEBUG - (True, 'PING 169.254.0.10 (169.254.0.10) 56(84) bytes of data.\r\n64 bytes from 169.254.0.10: icmp_seq=1 ttl=63 time=9.44 ms\r\n64 bytes from 169.254.0.10: icmp_seq=2 ttl=63 time=2.36 ms\r\n\r\n--- 169.254.0.10 ping statistics ---\r\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\r\nrtt min/avg/max/mdev = 2.362/5.901/9.441/3.540 ms')
2021-02-18 11:37:21,728 - INFO - Ping to Metadata IP 169.254.0.10 of VM ctest-vm1-test-05206063 passed
2021-02-18 11:37:21,809 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:21,810 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:21,837 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:22,044 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:27,045 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:27,045 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:27,073 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:27,287 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:32,288 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:32,289 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:32,348 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:32,553 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:37,555 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:37,555 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:37,587 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:37,794 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:42,795 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:42,796 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:42,823 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:43,029 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:48,030 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:48,030 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:48,067 - DEBUG - Error on ssh to ubuntu@169.254.0.10:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.10/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.10/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.10/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-18 11:37:48,269 - DEBUG - VM ctest-vm1-test-05206063 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-18 11:37:53,269 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-18 11:37:53,269 - DEBUG - Waiting to SSH to VM ctest-vm1-test-05206063, IP 10.10.10.3, Port 22
2021-02-18 11:37:53,363 - DEBUG - VM ctest-vm1-test-05206063 is ready for SSH connections
2021-02-18 11:37:53,363 - DEBUG - Running remote_cmd, Cmd : ifconfig | grep 10.10.10.3, host_string: ubuntu@169.254.0.10, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-18 11:37:53,364 - DEBUG - ifconfig | grep 10.10.10.3
2021-02-18 11:38:14,619 - DEBUG - inet addr:10.10.10.3  Bcast:10.10.10.255  Mask:255.255.255.0
2021-02-18 11:38:14,620 - DEBUG - Running remote_cmd, Cmd : python -c 'import socket;socket.getaddrinfo("ctest-vm1-test-05206063", None, socket.AF_INET6)', host_string: ubuntu@169.254.0.10, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-18 11:38:14,620 - DEBUG - python -c 'import socket;socket.getaddrinfo("ctest-vm1-test-05206063", None, socket.AF_INET6)'
2021-02-18 11:38:19,504 - DEBUG - Running remote_cmd, Cmd : ping -s 56 -c 3 -W 1  ctest-vm1-test-05206063, host_string: ubuntu@169.254.0.10, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-18 11:38:19,505 - DEBUG - ping -s 56 -c 3 -W 1  ctest-vm1-test-05206063
2021-02-18 11:38:22,384 - DEBUG - PING ctest-vm1-test-05206063.juniper.net (10.10.10.3) 56(84) bytes of data.
64 bytes from ctest-vm1-test-05206063.juniper.net (10.10.10.3): icmp_req=1 ttl=64 time=4.39 ms
64 bytes from ctest-vm1-test-05206063.juniper.net (10.10.10.3): icmp_req=2 ttl=64 time=0.240 ms
64 bytes from ctest-vm1-test-05206063.juniper.net (10.10.10.3): icmp_req=3 ttl=64 time=0.216 ms

--- ctest-vm1-test-05206063.juniper.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2006ms
rtt min/avg/max/mdev = 0.216/1.617/4.397/1.965 ms
2021-02-18 11:38:22,384 - INFO - Ping to IP ctest-vm1-test-05206063 from VM ctest-vm1-test-05206063 passed
2021-02-18 11:38:22,454 - INFO - Deleting VM ctest-vm1-test-05206063
2021-02-18 11:38:22,864 - INFO - Deleting VN ctest-vn1-vdns-92227502 
2021-02-18 11:38:22,966 - DEBUG - VN f14dd890-11a2-49fb-9add-31831038a179 still in use: Unable to complete operation on network f14dd890-11a2-49fb-9add-31831038a179. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-8ce8fd5c-654d-4ae3-b18e-359c44487875']
2021-02-18 11:38:22,966 - WARNING - Deleting VN ctest-vn1-vdns-92227502 failed..Will retry
2021-02-18 11:38:25,943 - DEBUG - Response for deleting network ()
2021-02-18 11:38:26,177 - DEBUG - Deleting VDNS Entry: ctest-vdns1-34558867
2021-02-18 11:38:26,292 - INFO - VDNS info: ['admin_domain', 'ctest-vdns1-34558867'] deleted successfully.
2021-02-18 11:38:26,292 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-18 11:38:26,317 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-18 11:38:26,532 - DEBUG - VDNS information not found in API server
2021-02-18 11:38:26,533 - INFO - VDNS information ctest-vdns1-34558867 removed from the API Server
2021-02-18 11:38:26,593 - INFO - VDNS information ctest-vdns1-34558867 removed in the Control node
2021-02-18 11:38:26,593 - DEBUG - Skipping the deletion of Project ['admin_domain', 'ctest-TestvDNSBasic0-74672136']
2021-02-18 11:38:28,626 - ERROR - KeyError
Python 3.6.8: /usr/bin/python3
Thu Feb 18 11:38:22 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestvDNSBasic0.test_vdns_ping_same_vn>
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>
args = ()
kwargs = {}

 /contrail-test/scripts/vdns/test_vdns_basic.py in test_vdns_ping_same_vn(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>)
  127             vm_dns_exp_data = [{'rec_data': vm_ip, 'rec_type': 'A', 'rec_class': 'IN', 'rec_ttl': str(
  128                 ttl), 'rec_name': rec_name, 'installed': 'yes', 'zone': domain_name}, {'rec_data': rec_name, 'rec_type': 'PTR', 'rec_class': 'IN', 'rec_ttl': str(ttl), 'rec_name': vm_rev_ip, 'installed': 'yes', 'zone': rev_zone}]
  129             self.verify_vm_dns_data(vm_dns_exp_data, assigned_dns_ips[0])
  130             vm_dns_exp_data = []
  131         # ping between two vms which are in same subnets by using name.
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>
self.verify_vm_dns_data = <bound method BasevDNSTest.verify_vm_dns_data of...ite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>>
vm_dns_exp_data = [{'installed': 'yes', 'rec_class': 'IN', 'rec_data': '10.10.10.3', 'rec_name': 'ctest-vm1-test-05206063.juniper.net', 'rec_ttl': '100', 'rec_type': 'A', 'zone': 'juniper.net'}, {'installed': 'yes', 'rec_class': 'IN', 'rec_data': 'ctest-vm1-test-05206063.juniper.net', 'rec_name': '3.10.10.10.in-addr.arpa', 'rec_ttl': '100', 'rec_type': 'PTR', 'zone': '10.10.10.in-addr.arpa'}]
assigned_dns_ips = ['192.168.27.20', '192.168.27.29', '192.168.27.34']

 /contrail-test/common/vdns/base.py in verify_vm_dns_data(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>, vm_dns_exp_data=[{'installed': 'yes', 'rec_class': 'IN', 'rec_data': '10.10.10.3', 'rec_name': 'ctest-vm1-test-05206063.juniper.net', 'rec_ttl': '100', 'rec_type': 'A', 'zone': 'juniper.net'}, {'installed': 'yes', 'rec_class': 'IN', 'rec_data': 'ctest-vm1-test-05206063.juniper.net', 'rec_name': '3.10.10.10.in-addr.arpa', 'rec_ttl': '100', 'rec_type': 'PTR', 'zone': '10.10.10.in-addr.arpa'}], dns_server_ip='192.168.27.20')
  438         result = True
  439         dns_data_list = []
  440         dns_server_ip = self.inputs.host_data[dns_server_ip]['host_ip']
  441         for bgp_ip in self.inputs.bgp_ips:
  442             dnsinspect_h = self.dnsagent_inspect[dns_server_ip]
dns_server_ip = '192.168.27.20'
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7f4ce0bf3fd0>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
self.inputs.host_data = {'192.168.27.19': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'k8s_cirros_cirros_default_17de7c97-01cd-4350-8401-3c2249528561_0': 'k8s_cirros_cirros_default_17de7c97-01cd-4350-8401-3c2249528561_0', 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_22': 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_22', 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_23': 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_23', 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_83e45f58-f119-4828-9b80-a681ecebeb2b_0': 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_83e45f58-f119-4828-9b80-a681ecebeb2b_0', 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_64575096-0773-4881-8bba-f16559ca5fd6_0': 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_64575096-0773-4881-8bba-f16559ca5fd6_0', 'k8s_nginx_nginx_default_e122a4d5-13d3-4b5c-a917-c375f5a0cafa_0': 'k8s_nginx_nginx_default_e122a4d5-13d3-4b5c-a917-c375f5a0cafa_0', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.19', 'control_data_ip': '192.168.27.19', 'data-ip': '192.168.27.19', 'fqname': 'noden19.maas', 'host_control_ip': '192.168.27.19', 'host_data_ip': '192.168.27.19', 'host_ip': '192.168.7.19', 'name': 'noden19', 'password': 'c0ntrail123', ...}, '192.168.27.9': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.9', 'control_data_ip': '192.168.27.9', 'data-ip': '192.168.27.9', 'fqname': 'nodec9.maas', 'host_control_ip': '192.168.27.9', 'host_data_ip': '192.168.27.9', 'host_ip': '192.168.7.9', 'name': 'nodec9', 'password': 'c0ntrail123', ...}, '192.168.7.18': {'containers': {'NAMES': 'NAMES', 'nuthan_test': 'nuthan_test', 'nuthan_test2': 'nuthan_test2', 'nuthan_test7': 'nuthan_test7', 'nuthan_test8': 'nuthan_test8', 'scale_test': 'scale_test', 'tf_test': 'tf_test'}, 'control-ip': '192.168.7.18', 'data-ip': '192.168.7.18', 'fqname': 'noden18.englab.juniper.net', 'host_control_ip': '192.168.7.18', 'host_data_ip': '192.168.7.18', 'host_ip': '192.168.7.18', 'name': 'noden18', 'password': 'c0ntrail123', 'roles': {}, ...}, '192.168.7.19': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'k8s_cirros_cirros_default_17de7c97-01cd-4350-8401-3c2249528561_0': 'k8s_cirros_cirros_default_17de7c97-01cd-4350-8401-3c2249528561_0', 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_22': 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_22', 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_23': 'k8s_coredns_coredns-6b59b8bd9f-f7hgs_kube-system_efbcc658-8b0f-4982-860d-15887593226b_23', 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_83e45f58-f119-4828-9b80-a681ecebeb2b_0': 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_83e45f58-f119-4828-9b80-a681ecebeb2b_0', 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_64575096-0773-4881-8bba-f16559ca5fd6_0': 'k8s_k8s-keystone-auth_k8s-keystone-auth-bd454d69...ube-system_64575096-0773-4881-8bba-f16559ca5fd6_0', 'k8s_nginx_nginx_default_e122a4d5-13d3-4b5c-a917-c375f5a0cafa_0': 'k8s_nginx_nginx_default_e122a4d5-13d3-4b5c-a917-c375f5a0cafa_0', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.19', 'control_data_ip': '192.168.27.19', 'data-ip': '192.168.27.19', 'fqname': 'noden19.maas', 'host_control_ip': '192.168.27.19', 'host_data_ip': '192.168.27.19', 'host_ip': '192.168.7.19', 'name': 'noden19', 'password': 'c0ntrail123', ...}, '192.168.7.20': {'containers': {'NAMES': 'NAMES', 'alarmgen': 'analyticsalarm_alarm-gen_1', 'analytics-api': 'analytics_api_1', 'analytics-cassandra': 'analyticsdatabase_cassandra_1', 'analytics-nodemgr': 'analytics_nodemgr_1', 'analyticsalarm_kafka_1': 'analyticsalarm_kafka_1', 'analyticsdb-nodemgr': 'analyticsdatabase_nodemgr_1', 'api-server': 'configapi_api_1', 'collector': 'analytics_collector_1', 'config-cassandra': 'configdatabase_cassandra_1', ...}, 'control-ip': '192.168.7.20', 'data-ip': '192.168.7.20', 'fqname': 'noden20.maas', 'host_control_ip': '192.168.7.20', 'host_data_ip': '192.168.7.20', 'host_ip': '192.168.7.20', 'ips': ['192.168.27.20', '172.17.0.1', '192.168.7.20'], 'name': 'noden20', 'password': 'c0ntrail123', ...}, '192.168.7.29': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'alarmgen': 'analyticsalarm_alarm-gen_1', 'analytics-api': 'analytics_api_1', 'analytics-cassandra': 'analyticsdatabase_cassandra_1', 'analytics-nodemgr': 'analytics_nodemgr_1', 'analyticsalarm_kafka_1': 'analyticsalarm_kafka_1', 'analyticsdb-nodemgr': 'analyticsdatabase_nodemgr_1', 'api-server': 'configapi_api_1', 'collector': 'analytics_collector_1', ...}, 'control-ip': '192.168.7.29', 'data-ip': '192.168.7.29', 'fqname': 'noden29.maas', 'host_control_ip': '192.168.7.29', 'host_data_ip': '192.168.7.29', 'host_ip': '192.168.7.29', 'ips': ['192.168.7.29', '172.17.0.1', '192.168.27.29'], 'name': 'noden29', 'password': 'c0ntrail123', ...}, '192.168.7.34': {'containers': {'NAMES': 'NAMES', 'alarmgen': 'analyticsalarm_alarm-gen_1', 'analytics-api': 'analytics_api_1', 'analytics-cassandra': 'analyticsdatabase_cassandra_1', 'analytics-nodemgr': 'analytics_nodemgr_1', 'analyticsalarm_kafka_1': 'analyticsalarm_kafka_1', 'analyticsdb-nodemgr': 'analyticsdatabase_nodemgr_1', 'api-server': 'configapi_api_1', 'collector': 'analytics_collector_1', 'config-cassandra': 'configdatabase_cassandra_1', ...}, 'control-ip': '192.168.7.34', 'data-ip': '192.168.7.34', 'fqname': 'nodei34.maas', 'host_control_ip': '192.168.7.34', 'host_data_ip': '192.168.7.34', 'host_ip': '192.168.7.34', 'ips': ['192.168.7.34', '192.168.27.34', '172.17.0.1'], 'name': 'nodei34', 'password': 'c0ntrail123', ...}, '192.168.7.9': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.9', 'control_data_ip': '192.168.27.9', 'data-ip': '192.168.27.9', 'fqname': 'nodec9.maas', 'host_control_ip': '192.168.27.9', 'host_data_ip': '192.168.27.9', 'host_ip': '192.168.7.9', 'name': 'nodec9', 'password': 'c0ntrail123', ...}, 'nodec9': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.9', 'control_data_ip': '192.168.27.9', 'data-ip': '192.168.27.9', 'fqname': 'nodec9.maas', 'host_control_ip': '192.168.27.9', 'host_data_ip': '192.168.27.9', 'host_ip': '192.168.7.9', 'name': 'nodec9', 'password': 'c0ntrail123', ...}, 'nodec9.maas': {'containers': {'NAMES': 'NAMES', 'agent': 'vrouter_vrouter-agent_1', 'vrouter-nodemgr': 'vrouter_nodemgr_1'}, 'control-ip': '192.168.27.9', 'control_data_ip': '192.168.27.9', 'data-ip': '192.168.27.9', 'fqname': 'nodec9.maas', 'host_control_ip': '192.168.27.9', 'host_data_ip': '192.168.27.9', 'host_ip': '192.168.7.9', 'name': 'nodec9', 'password': 'c0ntrail123', ...}, ...}
KeyError: '192.168.27.20'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('192.168.27.20',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/vdns/test_vdns_basic.py", line 129, in test_vdns_ping_same_vn
    self.verify_vm_dns_data(vm_dns_exp_data, assigned_dns_ips[0])
  File "/contrail-test/common/vdns/base.py", line 440, in verify_vm_dns_data
    dns_server_ip = self.inputs.host_data[dns_server_ip]['host_ip']
KeyError: '192.168.27.20'



2021-02-18 11:38:28,659 - DEBUG - No XMPP flaps were noticed during the test
2021-02-18 11:38:28,659 - INFO - 
2021-02-18 11:38:28,659 - INFO - END TEST : test_vdns_ping_same_vn : FAILED[0:02:42]
2021-02-18 11:38:28,659 - INFO - --------------------------------------------------------------------------------
2021-02-18 11:38:32,520 - INFO - Deleted project: ctest-TestvDNSBasic0-74672136, ID : e7a1dac9-dcf1-4e37-bfe2-7a87008dcebd 
